### PR TITLE
Responding to feedback

### PR DESCRIPTION
**Pull request by rynowak**
Responding to a few of your comments with some additional suggestiongs...

> When I set the folder structure in the configuration, it didn't work unless I had the pages in a "Pages" folder, without including that in the config

This is a setting. It's global (all file providers), so I guess you'll have to think about if you want the default setting or not. See the startup code. 

>When I included the additional physical file provider, the ones included under the app root stopped resolving. I tried adding a second physical file provider (so we're up to three now including the app root one) and only the first one added seems to allow pages to be resolved

I can't reproduce this. Based on my updated code, it works on my machine 😁

> Inside the services.Configure<RazorViewEngineOptions> block, options.FileProviders is an empty collection, it seems the built-in provider is added some time after this stage, because when I inject IRazorViewEngineFileProviderAccessor, I see all the providers which I added, with the built-in one at the last index. Only the first in the collection is looked at and serves pages

Yeah this was bad advice from me to put the code in this order. Configure callbacks are run in order, so putting your registration before MVC means it runs before MVC. I updated this code to the example I would typically show.

### CODE REVIEW

**Comment by sparkeh9** [comment]
Thanks for the clarification on the ordering - I knew that the pipeline (the .UseXx() stuff) order mattered, but I didn't realise the order of the .AddXx() mattered so much.
I'll give your updated code a try and see if it was the ordering which was skewing the results 👍

Last question (Promise 😁) Is there a way to exclude razor pages from view compilation? Embedded razor views which work with controllers are expected to be static, but RazorPages (in my particular use case) should be compiled on first access and recompiled if changed (like with a file watcher).

I'd just like to say that .Net Core and ASP.Net Core MVC is an incredible piece of work and is astonishingly extensible, you should be proud. It's reignited my love for the stack 👌

**Comment by rynowak** [comment]
> Last question (Promise 😁) Is there a way to exclude razor pages from view compilation? Embedded razor views which work with controllers are expected to be static, but RazorPages (in my particular use case) should be compiled on first access and recompiled if changed (like with a file watcher).

View Compilation is a build-time feature - so if you have additional file providers that are wired up when you start the application, those already won't participate in the build.

If you need to exclude specific files under your app's directory structure from build time compilation, it's going to be really tricky because you'll have to write a bunch of MSbuild. It would be easier to just turn off build-time compilation entirely. `<RazorCompileOnBuild>false</RazorCompileOnBuild>`

**Comment by sparkeh9** [comment]
Hi @rynowak I just tested your latest pull request and in debug mode everything works great 👌

When I publish in Release mode, razor pages brought in from an external directory show this message:
image

**Comment by rynowak** [comment]
I think you will also need to set `<CopyRefAssembliesToPublishDirectory></CopyRefAssembliesToPublishDirectory>` 

https://github.com/aspnet/Razor/blob/master/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props#L46

**Comment by sparkeh9** [comment]
Brilliant thanks 😎

One other minor thing I noticed - I usually use convention routing for my MVC controllers, when generating a URL from a RazorPage, this does not seem to work unless I explicitly add a Route attribute.

I've tried this with `app.UseMvcWithDefaultRoute();` as well as

```
            app.UseMvc( routes =>
                        {
                            routes.MapRoute(
                                            name: "default",
                                            template: "{controller=Home}/{action=Index}/{id?}");
                        });
```

**Comment by rynowak** [comment]
> One other minor thing I noticed - I usually use convention routing for my MVC controllers, when generating a URL from a RazorPage, this does not seem to work unless I explicitly add a Route attribute.

Can you provide an example? What code is failing to generate a URL?

What you put there is literally the same as `UseMvcWithDefaultRoute()`

**Pull request merged**
